<template>
  <div class="mt-5">
    <div class="grid grid-cols-4 p-4 ">
        <div class="grid place-content-center">
        <button
        class="grid place-content-center bg-gradient-to-tr from-lime-400 to-lime-700 ring-0 ring-green-600 drop-shadow-lg shadow-lg shadow-lime-500/80 bounce-in-top size-64 rounded-full"
        @click="irANuevaPagina"
      >
        <p class="text-2xl font-sans font-semibold ">3 sets</p>
      </button>
        </div>
        <div class="grid place-content-center">
      <button
      class="bg-gradient-to-tr from-yellow-400 to-amber-700 ring-0 ring-green-600 drop-shadow-lg shadow-lg shadow-amber-500/80 bounce-in-top size-64 rounded-full "
      @click="irANuevaPagina"
      >
      <p class="text-2xl text-yellow-200 font-sans font-semibold drop-shadow-lg">3 sets ORO</p>

       
      </button>
</div>
<div class="grid place-content-center">

      <button
      @click="irAOroDos"
      class=" grid place-content-center bg-gradient-to-tr from-lime-400 to-lime-700 ring-0 ring-green-600 drop-shadow-lg shadow-lg shadow-lime-500/80 bounce-in-top size-64 rounded-full"

      >
      <p class="text-2xl font-sans font-semibold">2 sets Súpertie</p>

      </button>
</div>
<div class="grid place-content-center">

      <button
      @click="irAOroDos"
      class="bg-gradient-to-tr from-yellow-400 to-amber-700 ring-0 ring-green-600 drop-shadow-lg shadow-lg shadow-amber-500/80 bounce-in-top size-64 rounded-full"

      >
      <p class="text-2xl text-yellow-200 font-sans font-semibold drop-shadow-xl">2 sets Súpertie ORO</p>

      </button>
      </div>
    </div>
  </div>
</template>

<script>
export default {
    methods: {
        irANuevaPagina() {
      // Navegar a la nueva página utilizando Vue Router
      this.$router.push('/OroTres');
    },

    irAOroDos() {
      // Navegar a la nueva página utilizando Vue Router
      this.$router.push('/OroDos');
    }
    
},
}
</script>

<style>
.bounce-in-top {
  -webkit-animation: bounce-in-top 2s both;
  animation: bounce-in-top 2s both;
}
/* ----------------------------------------------
 * Generated by Animista on 2024-1-29 12:21:7
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation bounce-in-top
 * ----------------------------------------
 */
@-webkit-keyframes bounce-in-top {
  0% {
    -webkit-transform: translateY(-500px);
    transform: translateY(-500px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
    opacity: 0;
  }
  38% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
    opacity: 1;
  }
  55% {
    -webkit-transform: translateY(-65px);
    transform: translateY(-65px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  72% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  81% {
    -webkit-transform: translateY(-28px);
    transform: translateY(-28px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  90% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  95% {
    -webkit-transform: translateY(-8px);
    transform: translateY(-8px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
}
@keyframes bounce-in-top {
  0% {
    -webkit-transform: translateY(-500px);
    transform: translateY(-500px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
    opacity: 0;
  }
  38% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
    opacity: 1;
  }
  55% {
    -webkit-transform: translateY(-65px);
    transform: translateY(-65px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  72% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  81% {
    -webkit-transform: translateY(-28px);
    transform: translateY(-28px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  90% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  95% {
    -webkit-transform: translateY(-8px);
    transform: translateY(-8px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
}
</style>
