<template>
  <div class="">
    <div class="grid grid-cols-2 ">
        
        <div class="grid place-content-center p-4">
            <button
      class="bg-gradient-to-tr from-black to-white ring-0  drop-shadow-lg shadow-lg shadow-white/80 bounce-in-top size-64 rounded-full "
      @click="irATres"
      >
      <p class="text-2xl text-black font-sans font-semibold drop-shadow-lg">Modo 3 sets</p>
      </button>
      
      
</div>
<div class="grid place-content-center">
    <button
      class="bg-gradient-to-tr from-gray-800 to-rose-700 ring-0  drop-shadow-lg shadow-lg shadow-pink-400/80 bounce-in-top size-64 rounded-full "
      @click="irANuevaPagina"
      >
      <p class="text-2xl text-white font-sans font-semibold drop-shadow-lg">Modo 2 sets</p>
      </button>
      
</div>


    </div>
  </div>
</template>

<script>
export default {
    methods: {
        irANuevaPagina() {
      // Navegar a la nueva página utilizando Vue Router
      this.$router.push('/OroDos');
    },
    irATres() {
      // Navegar a la nueva página utilizando Vue Router
      this.$router.push('/OroTres');
    },
},
}
</script>

<style>
.bounce-in-top {
  -webkit-animation: bounce-in-top 2s both;
  animation: bounce-in-top 2s both;
}
/* ----------------------------------------------
 * Generated by Animista on 2024-1-29 12:21:7
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation bounce-in-top
 * ----------------------------------------
 */
@-webkit-keyframes bounce-in-top {
  0% {
    -webkit-transform: translateY(-500px);
    transform: translateY(-500px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
    opacity: 0;
  }
  38% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
    opacity: 1;
  }
  55% {
    -webkit-transform: translateY(-65px);
    transform: translateY(-65px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  72% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  81% {
    -webkit-transform: translateY(-28px);
    transform: translateY(-28px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  90% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  95% {
    -webkit-transform: translateY(-8px);
    transform: translateY(-8px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
}
@keyframes bounce-in-top {
  0% {
    -webkit-transform: translateY(-500px);
    transform: translateY(-500px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
    opacity: 0;
  }
  38% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
    opacity: 1;
  }
  55% {
    -webkit-transform: translateY(-65px);
    transform: translateY(-65px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  72% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  81% {
    -webkit-transform: translateY(-28px);
    transform: translateY(-28px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  90% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  95% {
    -webkit-transform: translateY(-8px);
    transform: translateY(-8px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
}
</style>
