<template>
    <div class="grid content-center">
  <banner-top />
</div>

<div class="grid justify-center gap-4 text-focus-in">
        <div class="grid gap-4 justify-center">
        
        <img :src="marca" class="w-48 h-32" />
  </div>
        <div class="grid justify-center">
                <h1 class="text-4xl font-bold text-rose-600 text-stroke text-stroke-2 ">Torneo Navidad organizado por:</h1>
        </div>
  <!-- Contenedor para las imágenes -->
  <div class="grid grid-cols-2 justify-center">
        
        <img :src="ko" class="w-64 h-64 heartbeat border" />
    <img :src="principal" class="w-64 h-64 heartbeat border" />
  </div>

  <!-- Botón especial debajo de las imágenes -->
  <div class=" justify-center">
    <boton-especial />
  </div>
</div>

  
</template>

<script >
import BannerTop from './BannerTop.vue';
import BotonEspecial from './BotonEspecial.vue';
import MarcaAgua from './MarcaAgua.vue';
export default {
        data() {
    return {
      // Inicializa la variable rutaImagen con la ruta de la imagen
      principal: "/12.png",
      ko: "/11.png",
      marca: "/pavel.png",

    };
  },
  components: { BannerTop, BotonEspecial,MarcaAgua },
  };
</script>

<style>
h1 {
      font-size: 10rem;               /* Tamaño del texto */
      font-weight: bold;             /* Grosor del texto */
      color: #dc2626;                /* Color equivalente a text-rose-600 */
      -webkit-text-stroke: 1px white; /* Borde blanco */
      text-align: center;            /* Centrar el texto */
    }
.text-focus-in {
	-webkit-animation: text-focus-in 1s cubic-bezier(0.550, 0.085, 0.680, 0.530) 1s both;
	        animation: text-focus-in 1s cubic-bezier(0.550, 0.085, 0.680, 0.530) 1s both;
}
.heartbeat {
	-webkit-animation: heartbeat 1s ease-in-out 4s infinite both;
	        animation: heartbeat 2.5s ease-in-out 4s infinite both;
}
/* ----------------------------------------------
 * Generated by Animista on 2024-2-1 11:37:9
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-focus-in
 * ----------------------------------------
 */
 /* ----------------------------------------------
 * Generated by Animista on 2024-2-1 11:40:47
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation heartbeat
 * ----------------------------------------
 */
@-webkit-keyframes heartbeat {
  from {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-transform-origin: center center;
            transform-origin: center center;
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  10% {
    -webkit-transform: scale(0.91);
            transform: scale(0.91);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  17% {
    -webkit-transform: scale(0.98);
            transform: scale(0.98);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  33% {
    -webkit-transform: scale(0.87);
            transform: scale(0.87);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  45% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
}
@keyframes heartbeat {
  from {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-transform-origin: center center;
            transform-origin: center center;
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  10% {
    -webkit-transform: scale(0.91);
            transform: scale(0.91);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  17% {
    -webkit-transform: scale(0.98);
            transform: scale(0.98);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  33% {
    -webkit-transform: scale(0.87);
            transform: scale(0.87);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  45% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
}

 @-webkit-keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}
@keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}

</style>
